# Generated by Django 5.0.4 on 2024-04-29 01:55

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('email', models.CharField(max_length=70, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nasc', models.CharField(max_length=10, verbose_name='Data de nascimento')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
